-- ============================================================
-- Seed: lista principal de bares
-- CDMX (25) · Riviera Maya (24) · Guadalajara (23)
-- ============================================================
INSERT INTO bars (id, name, city, address, category, image_url, state_id, city_id, hero_drinks, google_maps_url)
VALUES

  -- ── CDMX ─────────────────────────────────────────────────

  ('arrrco-cdmx',
    'ARRRCO', 'Juárez',
    'C. Lisboa 3C, Juárez, Cuauhtémoc, 06600 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'juarez',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/Gyf6gFrcq9HrgXit5'),

  ('balcon-del-zocalo-cdmx',
    'BALCON DEL ZOCALO', 'Centro Histórico',
    'Av. 5 de Mayo 61, Centro Histórico de la Cdad. de México, Cuauhtémoc, 06000 CDMX',
    'Rooftop', NULL, 'cdmx', 'centro-historico',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/G9z7HWTiARn436qN8'),

  ('baltra-cdmx',
    'BALTRA', 'Condesa',
    'Iztaccihuatl 36D, Colonia Condesa, Cuauhtémoc, 06100 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'condesa',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/oVkGwPcpboM4LKWg8'),

  ('basico-cdmx',
    'BASICO', 'Roma',
    'Av Sonora 84, Centro Urbano Pdte. Juárez, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/3GCjx6CkuLiH1Jwz8'),

  ('bijou-cdmx',
    'BIJOU', 'Roma',
    'Av. Sonora 189, Hipódromo, Cuauhtemoc, 06100',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/4pnLzriaYTptGFwZA'),

  ('cafe-tacobar-cdmx',
    'CAFÉ TACOBAR', 'Roma',
    'Av Oaxaca 12, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/7vxneSKDSpNojif3A'),

  ('carmin-cdmx',
    'CARMIN', 'Coyoacán',
    'Malintzin 155, Del Carmen, Coyoacán, 04100 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'coyoacan',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/2fBNn6gTwQ3BPebW9'),

  ('corazon-de-maguey-cdmx',
    'CORAZON DE MAGUEY', 'Coyoacán',
    'Parque Centenario 9A, Coyoacán, 04000 Ciudad de México, CDMX',
    'Mezcaleria', NULL, 'cdmx', 'coyoacan',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/qmmZhr7erq5dvH657'),

  ('d-margarita-cdmx',
    'D. MARGARITA', 'Roma',
    'Córdoba 115, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/T5W93wFgUF4o7zaF8'),

  ('danzantes-cdmx',
    'DANZANTES', 'Coyoacán',
    'Parque Centenario 12, Coyoacán TNT, Coyoacán, 04000 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'coyoacan',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/Y1U2UMhTsqRDLmrb6'),

  ('foma-cdmx',
    'FOMA', 'Roma',
    'San Luis Potosí 37, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/xLJj7bxgikeZMagk8'),

  ('hotel-mondrian-cdmx',
    'HOTEL MONDRIAN', 'Condesa',
    'Aguascalientes 156, Colonia Condesa, Cuauhtémoc, 06100 Ciudad de México, CDMX',
    'Rooftop', NULL, 'cdmx', 'condesa',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/77STpnbdaqinR72y8'),

  ('kaito-cdmx',
    'KAITO', 'Juárez',
    'Hamburgo 70B, Juárez, Cuauhtémoc, 06600 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'juarez',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/1TiyF19ii5tyKFGY7'),

  ('la-unica-cdmx',
    'LA UNICA', 'Polanco',
    'Anatole France 98, Polanco, Polanco III Secc, Miguel Hidalgo, 11550 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'polanco',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/v3UJMmX88YL9LTji7'),

  ('lavista-cdmx',
    'LAVISTA', 'Roma',
    'Puebla 90, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/W88KUuaXCJrFxHH98'),

  ('less-is-more-cdmx',
    'LESS IS MORE', 'Roma',
    'Puebla 289, Roma Nte., Cuauhtémoc, 06700 Cuauhtémoc, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/HEbsXm1K4rWK2guE7'),

  ('limantour-polanco',
    'LIMANTOUR', 'Polanco',
    'Oscar Wilde 9, Polanco, Polanco III Secc, Miguel Hidalgo, 11560 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma-polanco',
    ARRAY['Margarita al Pastor'],
    'https://maps.app.goo.gl/uFDS8CbmENEoaZRt7'),

  ('ling-ling-cdmx',
    'Ling Ling by Hakkasan', 'Reforma',
    'Av. P.º de la Reforma 509-Piso 56, Cuauhtémoc, 06500 Ciudad de México, CDMX. Dentro del Hotel Ritz-Carlton',
    'Rooftop', NULL, 'cdmx', 'reforma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/P1sikYgePpXiysNd9'),

  ('long-story-short-cdmx',
    'LONG STORY SHORT', 'Juárez',
    'Florencia 51-Local B2, Juárez, Cuauhtémoc, 06600 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'juarez',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/bJTZQect4tKhgfw7A'),

  ('nostos-pedregal-cdmx',
    'NOSTOS', 'Pedregal',
    'Artz Blvd. 14, Jardines del Pedregal, Álvaro Obregón, 01900 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'pedregal',
    ARRAY['Margarita Griega'],
    'https://maps.app.goo.gl/udZjue1K5E1pRfe67'),

  ('nostos-lomas-cdmx',
    'NOSTOS', 'Lomas',
    'Monte Athos 415, Lomas de Chapultepec, Miguel Hidalgo, 11000 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'lomas',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/zfuHVVL379GyfdgK9'),

  ('ritmo-cafe-cdmx',
    'RITMO CAFÉ', 'Roma',
    'Medellín 78, Roma Nte., Cuauhtémoc, 06700 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'roma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/ji8o4b43hsE7tovn9'),

  ('ritz-carlton-cdmx',
    'RITZ CARLTON', 'Reforma',
    'Av. P.º de la Reforma 509-Piso 56, Cuauhtémoc, 06500 Ciudad de México, CDMX',
    'Rooftop', NULL, 'cdmx', 'reforma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/wbHXkStY6HdEsncY7'),

  ('septimo-coyoacan-cdmx',
    'SEPTIMO COYOACAN', 'Coyoacán',
    'Calle Pdte. Carranza 106, Coyoacán, 04000 Ciudad de México, CDMX',
    'Bar de cocteles', NULL, 'cdmx', 'coyoacan',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/c9jW7spSjn54gXYn9'),

  ('st-regis-cdmx',
    'ST REGIS HOTEL', 'Reforma',
    'Av. P.º de la Reforma 439, Cuauhtémoc, 06500 Ciudad de México, CDMX',
    'Rooftop', NULL, 'cdmx', 'reforma',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/fZJWaJgzBeiNRDHFA'),

  -- ── RIVIERA MAYA ─────────────────────────────────────────

  ('aereo-cafe-rm',
    'AEREO CAFÉ', 'Riviera Maya',
    '15 Avenida Sur 131, Centro, 77713 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'riviera-maya',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/kU7dTEp4LzhTxxsTA'),

  ('aguachiles-constituyentes-rm',
    'AGUACHILES CONSTITUYENTES', 'Playa del Carmen',
    'Av. Constituyentes Manzana 63-Lote 3, Centro, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Especial'],
    'https://maps.app.goo.gl/YFh8MdY6r71RxHWb7'),

  ('arca-tulum',
    'ARCA', 'Tulum',
    'Carr. Tulum-Boca Paila km 7.6, Tulum Beach, 77780 Tulum, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'tulum',
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/RHVQW58oXfQiGMhh6'),

  ('autoctona-cancun',
    'AUTOCTONA', 'Cancún',
    'Av. Yaxchilán, Jasmines 31, 77500 Cancún, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'cancun',
    ARRAY['HUNAC'],
    'https://maps.app.goo.gl/zGopRuANgUamP9V57'),

  ('beach-club-vivid-rm',
    'BEACH CLUB VIVID', 'Cancún',
    'Av. Constituyentes 2, Gonzalo Guerrero, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'cancun',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/LYFtnSJfkXS4GnK68'),

  ('bovinos-cancun',
    'BOVINOS CANCUN', 'Cancún',
    'Av Yaxchilán 17, Coral Rivera, 77500 Cancún, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'cancun',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/FGpucS74x4mfgpi96'),

  ('bovinos-playa',
    'BOVINOS PLAYA', 'Playa del Carmen',
    'Av. 10, Calle 12 Nte con, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/hWsGqVsrMa9qe6A29'),

  ('campo-golf-gran-coyote-playa',
    'CAMPO DE GOLF GRAN COYOTE', 'Playa del Carmen',
    'México 307 km 294, Solidaridad, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Coyote Margarita'],
    'https://maps.app.goo.gl/ofBGkXtJpPsx2bAj7'),

  ('chable-maroma-rm',
    'CHABLE MAROMA', 'Riviera Maya',
    'Camino predio Manzana 002 Lote 006, 77710 Punta Maroma, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'riviera-maya',
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/5JHTcBgYD4UWqp1d6'),

  ('costa-corasol-playa',
    'COSTA / CORASOL', 'Playa del Carmen',
    'Cancún, México 307 Km 294, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/swhrztRqQdcCdhDD6'),

  ('fragata-playa',
    'FRAGATA', 'Playa del Carmen',
    'Calle Albatros Esquina Con Calle Flamingos Sin Número, Manzana 7 Lote 1, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Flight'],
    'https://maps.app.goo.gl/WHpj8zLYXXQ2Jvi68'),

  ('harrys-cancun',
    'HARRY´S', 'Cancún',
    'Km. 14.2, Kukulkan 1, Zona Hotelera, 77500 Cancún, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'cancun',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/uZgHXuqaNjUxG1uZ8'),

  ('hotel-regist-rm',
    'HOTEL REGIST', 'Riviera Maya',
    'Riviera Maya, Q.R.',
    'Rooftop', NULL, 'riviera-maya', 'riviera-maya',
    ARRAY['Mezcal Logia'],
    NULL),

  ('hotel-banyan-tree-playa',
    'HOTEL BANYAN TREE', 'Playa del Carmen',
    'Carretera Federal Chetumal-Puerto Juárez KM 298 Riviera Maya, 77710 Playa del Carmen, Q.R.',
    'Rooftop', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/Uc3x1xVLnZLgPXir9'),

  ('hotel-mirabel-cancun',
    'HOTEL MIRABEL', 'Cancún',
    'Av. Constituyentes 2-Oriente, zona dos extendida, Centro, 76000 Santiago de Querétaro, Qro.',
    'Rooftop', NULL, 'riviera-maya', 'cancun',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/pKjoUg528SJSsUUz9'),

  ('hotel-mousai-cancun',
    'HOTEL MOUSAI', 'Cancún',
    'Carretera a Punta Sam Km. 5.2 Mza 9 Lote 3 Zona Continental de Costa Mujeres, 77400 Cancún, Q.R.',
    'Rooftop', NULL, 'riviera-maya', 'cancun',
    ARRAY['Smokyrita'],
    'https://maps.app.goo.gl/DXJSv16Pwnzzssrh8'),

  ('hotel-vivid-cancun',
    'HOTEL VIVID', 'Cancún',
    'Blvd. Kukulcan Km.16.5-Lotes 56-A-1 y 56-A-2, Segunda Etapa Turística, Zona Hotelera, 77500 Cancún, Q.R.',
    'Rooftop', NULL, 'riviera-maya', 'cancun',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/9smC5c9XQ62mzxwb8'),

  ('karens-playa',
    'KAREN''S', 'Playa del Carmen',
    'Quinta Avenida, Centro, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Cadilac'],
    'https://maps.app.goo.gl/T576kQ58SjTyQ6w57'),

  ('la-perla-pixan-playa',
    'LA PERLA PIXAN', 'Playa del Carmen',
    'Calle 38 Norte Entre 5ta y la playa, Gonzalo Guerrero, 77720 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Flight'],
    'https://maps.app.goo.gl/bfzjbAk5w1Fv66nP7'),

  ('mexico-loco-playa',
    'MEXICO LOCO', 'Playa del Carmen',
    'Av. Benito Júarez Quinta Avenida esquina, Av Benito Juárez, 77560 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Premium'],
    'https://maps.app.goo.gl/o4vPqrAhnT7PGkkN8'),

  ('quinta-piedra-playa',
    'QUINTA PIEDRA', 'Playa del Carmen',
    '5 Av. Nte. 5, Gonzalo Guerrero, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Margarita Cadilac'],
    'https://maps.app.goo.gl/69mcfEQ4sLieNmCHA'),

  ('secret-moxche-playa',
    'SECRET MOXCHE', 'Playa del Carmen',
    'Carr. Tulum - Cancún Supermanzana Km 294, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/PwKVk4Tc7rCkDfmW6'),

  ('vagabuda-5av-playa',
    'VAGABUDA 5 AV', 'Playa del Carmen',
    '5ta Av entre 24 Y 26, Quinta Avenida, Centro, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY['Perfec Patron'],
    'https://maps.app.goo.gl/TyXEAqGAKm6tkAcs6'),

  ('zapote-playa',
    'ZAPOTE', 'Playa del Carmen',
    'Carretera Tulum - Cancún Carretera Federal, Cancun - Chetumal Km 298, 77710 Playa del Carmen, Q.R.',
    'Bar de cocteles', NULL, 'riviera-maya', 'playa-del-carmen',
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/h4hBXDCv7xRyLcey9'),

  -- ── GUADALAJARA ──────────────────────────────────────────

  ('alcalde-gdl',
    'Alcalde', 'Guadalajara',
    'Av. México 2903, Vallarta Nte., 44690 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY[]::TEXT[],
    'https://maps.app.goo.gl/VNNTsLk3F4zadR4X7'),

  ('almacen-del-bife-puerta-hierro',
    'Almacén del Bife', 'Zapopan',
    'Blvd. Puerta de Hierro 4965, Puerta de Hierro, 45116 Zapopan, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clasica', 'Cazuelita Altos'],
    'https://maps.app.goo.gl/41bVyhA441n2FSmQ7'),

  ('almacen-del-bife-providencia',
    'Almacén del Bife', 'Guadalajara',
    'São Paulo 2367, Providencia, 44630 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clasica', 'Cazuelita Altos'],
    'https://maps.app.goo.gl/VyduNq4X5a8mj94W8'),

  ('almacen-del-bife-punto-sur',
    'Almacén del Bife', 'Guadalajara',
    'Av. Punto Sur 312, 45645 Tlajomulco de Zúñiga, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clasica', 'Cazuelita Altos'],
    'https://maps.app.goo.gl/xSpVhQCJtvHkmCVr8'),

  ('bruna-gdl',
    'Bruna', 'Guadalajara',
    'C. Miguel Lerdo de Tejada 2418, Lafayette, 44150 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Cazuelita'],
    'https://maps.app.goo.gl/94FRLcHXG85RNqzj9'),

  ('carbon-zapopan',
    'Carbón', 'Zapopan',
    'Av Guadalupe 1261, Chapalita Oriente, 45040 Zapopan, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Frutos rojos'],
    'https://maps.app.goo.gl/EDZVKCTWBwfG6CEHA'),

  ('carbon-providencia',
    'Carbón', 'Guadalajara',
    'Av Providencia 2931, Providencia 4a. Secc, 44639 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Frutos rojos'],
    'https://maps.app.goo.gl/B9TYvVPCz5pgj4dF9'),

  ('casa-luna-tlaquepaque',
    'Casa Luna', 'Tlaquepaque',
    'Calle Independencia 211-int. A, Centro, 45500 San Pedro Tlaquepaque, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', 'tlaquepaque',
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/yox5YoMEf4oYgUFU8'),

  ('cielito-lindo-tlaquepaque',
    'Cielito Lindo', 'Tlaquepaque',
    'Calle Independencia 208, Centro, 45500 San Pedro Tlaquepaque, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', 'tlaquepaque',
    ARRAY['Margarita Clásica y Signature'],
    'https://maps.app.goo.gl/zXZELzcW2Y3mhAsP8'),

  ('galgo-gdl',
    'Galgo', 'Guadalajara',
    'Av Pablo Neruda 3055, Providencia 4a. Secc, 44639 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/GY1FNniaJuWH2qLe7'),

  ('geppeto-gdl',
    'Geppeto', 'Guadalajara',
    'C. Jesus Romero Flores 703, Jardines Alcalde, 44298 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clasica y de Sabores'],
    'https://maps.app.goo.gl/7dYyZ1WoPPqMUn857'),

  ('habanero-negro-gdl',
    'Habanero Negro', 'Guadalajara',
    'C. Manuel López Cotilla 1228-a, Col Americana, Americana, 44160 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/QGkvUL8aXcG8p9X98'),

  ('i-latina-gdl',
    'I Latina', 'Guadalajara',
    'Av Inglaterra 3128, Vallarta Poniente, 44110 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clásica', 'Margarita I'],
    'https://maps.app.goo.gl/ew7o1y85vSY7LFRr7'),

  ('luperca-gdl',
    'Luperca', 'Guadalajara',
    'Av. México 2895, Vallarta Nte., 44690 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita', 'Margarita Atanasio'],
    'https://maps.app.goo.gl/dwCMhg2vgREZUVzo8'),

  ('octo-gdl',
    'Octo', 'Guadalajara',
    'C. Miguel Lerdo de Tejada 2420, Lafayette, 44150 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Cazuelita'],
    'https://maps.app.goo.gl/Mw3EPM32vUjDjq5c7'),

  ('old-peter-gdl',
    'Old Peter', 'Guadalajara',
    'C. Pedro Moreno 1395, Col Americana, Americana, 44160 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/at17M9L3bGs4pexQ9'),

  ('oliveria-gdl',
    'Oliveria', 'Guadalajara',
    'Libertad 1852, Col Americana, Americana, 44160 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/DN6Wzok1w59rNasYA'),

  ('peter-brown-gdl',
    'Peter Brown', 'Guadalajara',
    'C. José María Morelos 1454, Ladrón de Guevara, Americana, 44600 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/u5w7JfooLrLnv6fi6'),

  ('peter-woods-gdl',
    'Peter Woods', 'Guadalajara',
    'Av. Adolfo López Mateos Sur Km. 15, San José del Tajo, El Palomar, 45645 Palomar, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/3jfzUFuK2uJiHvBQ8'),

  ('pinoccio-gdl',
    'Pinoccio', 'Guadalajara',
    'Av. Providencia 2916 Providencia 4a. Secc, Providencia, 44639 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/UMyv3g5kNiPrbxg18'),

  ('piso-7-gdl',
    'Piso 7', 'Guadalajara',
    'C. Colón 73, Zona Centro, 44100 Guadalajara, Jal.',
    'Rooftop', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Piso 7'],
    'https://maps.app.goo.gl/DuU24Qy49yuv7APr6'),

  ('umi-hand-roll-gdl',
    'Umi Hand Roll Experience', 'Zapopan',
    'Av. Empresarios 62, Puerta de Hierro, 45116 Zapopan, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita'],
    'https://maps.app.goo.gl/yuhSfHByCYtVpQtJ8'),

  ('xaneque-gdl',
    'Xaneque', 'Guadalajara',
    'Priv. Andrés Terán, Col Americana, Americana, 44600 Guadalajara, Jal.',
    'Bar de cocteles', NULL, 'guadalajara', NULL,
    ARRAY['Margarita Clasica', 'Margarita Sabor Verde', 'Margarita Sabor Rojo', 'Margarita Sabor Amarillo'],
    'https://maps.app.goo.gl/Q5pLUvHyoN2vhCa78')

ON CONFLICT (id) DO UPDATE SET
  name            = EXCLUDED.name,
  city            = EXCLUDED.city,
  address         = EXCLUDED.address,
  category        = EXCLUDED.category,
  state_id        = EXCLUDED.state_id,
  city_id         = EXCLUDED.city_id,
  hero_drinks     = EXCLUDED.hero_drinks,
  google_maps_url = EXCLUDED.google_maps_url;
